name: SAST Security Analysis

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  sast-analysis:
    name: Static Application Security Testing
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Compile project
      run: mvn clean compile test-compile -DskipTests

    - name: Run SpotBugs Analysis
      run: |
        mvn com.github.spotbugs:spotbugs-maven-plugin:4.8.2.0:spotbugs \
          -Dspotbugs.effort=Max \
          -Dspotbugs.threshold=Low \
          -Dspotbugs.xmlOutput=true \
          -Dspotbugs.xmlOutputDirectory=target/spotbugs
      continue-on-error: true

    - name: Upload SpotBugs results to GitHub
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: target/spotbugs/spotbugsXml.xml
        category: spotbugs
      continue-on-error: true

    - name: Run OWASP Dependency Check
      run: |
        mvn org.owasp:dependency-check-maven:9.0.7:check \
          -DdataDirectory=$HOME/owasp-data \
          -DautoUpdate=true \
          -DcveValidForHours=24 \
          -DfailBuildOnCVSS=7 \
          -Dformat=ALL \
          -DprettyPrint=true
      continue-on-error: true

    - name: Upload OWASP Dependency Check results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: target/dependency-check-report.sarif
        category: dependency-check
      continue-on-error: true

    - name: Archive security reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          target/spotbugs/
          target/dependency-check-report.*
        retention-days: 30
